/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pai;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import conexao.conexao;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class TelaEmprestimo extends javax.swing.JFrame {
   
    conexao con_cliente;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName());

    /**
     * Creates new form Tela1
     */
    public TelaEmprestimo() {
        initComponents();
        con_cliente = new conexao();
        con_cliente.conecta();
        
        con_cliente.executaSQL("select * from tbclientes order by cod");
preencherTabela();
posicionarRegistro();
jTable1.setAutoCreateRowSorter(true);// ativa a classificação ordenada da tabela
    }
public void preencherTabela() {

    jTable1.getColumnModel().getColumn(0).setPreferredWidth(4);
    jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(11);
    jTable1.getColumnModel().getColumn(3).setPreferredWidth(4);
    jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);

    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setNumRows(0);

    try {

        con_cliente.resultset.beforeFirst();

        while (con_cliente.resultset.next()) {

            modelo.addRow(new Object[]{
              con_cliente.resultset.getString("cod")
                    ,con_cliente.resultset.getString("nome")
                    ,con_cliente.resultset.getString("dt_nasc"
                    ),con_cliente.resultset.getString("telefone")
                    , con_cliente.resultset.getString("email")
            });
        }

    } catch (SQLException erro) {
      JOptionPane.showMessageDialog(null,"\n Erro ao listar dados da tabela!! :\n "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        
    }
}
public void posicionarRegistro() {
    try {
        con_cliente.resultset.first(); // posiciona no 1º registro da tabela
        mostrar_Dados(); // chama o método que irá buscar o dado da tabela
    } catch (SQLException erro) {
       JOptionPane.showMessageDialog(null,"Não foi possível posicionar no primeiro registro: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
    }
}
public void mostrar_Dados() {
    try {

        codigoU.setText(con_cliente.resultset.getString("cod")); // Associar a caixa de texto ao campo cod
        codigoL.setText(con_cliente.resultset.getString("nome")); // Associar a caixa de texto ao campo nome
        dataE.setText(con_cliente.resultset.getString("dt_nasc"));
        telefonet.setText(con_cliente.resultset.getString("telefone"));
        dataD.setText(con_cliente.resultset.getString("email"));

    } catch (SQLException erro) {
        JOptionPane.showMessageDialog(null,"Não localizou dados: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
    }
}private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {

    int linha_selecionada = jTable1.getSelectedRow();

    codigoU.setText(jTable1.getValueAt(linha_selecionada, 0).toString());
    codigoL.setText(jTable1.getValueAt(linha_selecionada, 1).toString());
    dataE.setText(jTable1.getValueAt(linha_selecionada, 2).toString());
    telefonet.setText(jTable1.getValueAt(linha_selecionada, 3).toString());
    dataD.setText(jTable1.getValueAt(linha_selecionada, 4).toString());

}
private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {

    // evento que sincroniza a grid com as setas do teclado

    int linha_selecionada = jTable1.getSelectedRow();

    codigoU.setText(jTable1.getValueAt(linha_selecionada, 0).toString());
    codigoL.setText(jTable1.getValueAt(linha_selecionada, 1).toString());
    dataE.setText(jTable1.getValueAt(linha_selecionada, 2).toString());
    telefonet.setText(jTable1.getValueAt(linha_selecionada, 3).toString());
    dataD.setText(jTable1.getValueAt(linha_selecionada, 4).toString());

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        codigo = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        codigoU = new javax.swing.JTextField();
        codigoL = new javax.swing.JTextField();
        dataE = new javax.swing.JTextField();
        telefonet = new javax.swing.JTextField();
        dataD = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnUtimo = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        JComboBox3 = new javax.swing.JComboBox<>();

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controle/Playback.gif"))); // NOI18N
        jButton6.addActionListener(this::jButton6ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Data Nascimento", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        codigo.setText("Código usuario:");

        nome.setText("Código Livro");

        data.setText("Data Expedição");

        telefone.setText("Data Devolução");

        dataD.addActionListener(this::dataDActionPerformed);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pai/Previous record.gif"))); // NOI18N
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pai/Playback.gif"))); // NOI18N
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pai/Play.gif"))); // NOI18N
        jButton8.addActionListener(this::jButton8ActionPerformed);

        btnUtimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pai/last recor.gif"))); // NOI18N
        btnUtimo.addActionListener(this::btnUtimoActionPerformed);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pai/Add.gif"))); // NOI18N
        jButton9.addActionListener(this::jButton9ActionPerformed);

        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pai/Save.gif"))); // NOI18N
        Cadastrar.addActionListener(this::CadastrarActionPerformed);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pai/Notes.gif"))); // NOI18N
        btnAlterar.addActionListener(this::btnAlterarActionPerformed);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pai/Delete.gif"))); // NOI18N
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        JComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tela Emprestimo\t\t\t", "Tela Cadastro", "Tela Cadastro de livros", "Tela Login", "Cadastrar livro" }));
        JComboBox3.addActionListener(this::JComboBox3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUtimo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigo)
                                    .addComponent(nome)
                                    .addComponent(data)
                                    .addComponent(telefone))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(codigoU, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigoL)
                                    .addComponent(dataE)
                                    .addComponent(telefonet)
                                    .addComponent(dataD, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(JComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo)
                    .addComponent(codigoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(codigoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(data)
                    .addComponent(dataE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefone)
                    .addComponent(telefonet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(dataD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUtimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addComponent(Cadastrar)
                        .addComponent(btnAlterar))
                    .addComponent(btnExcluir))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            con_cliente.resultset.first();
            mostrar_Dados();
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possível acessar o primeiro registro: "+erro);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            con_cliente.resultset.previous();
            mostrar_Dados();
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possível posicionar no registro anterior: "+erro);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            con_cliente.resultset.previous();
            mostrar_Dados();
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possível posicionar no registro anterior: "+erro);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            con_cliente.resultset.next();
            mostrar_Dados();
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possível posicionar no próximo registro: "+erro);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnUtimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtimoActionPerformed

        try {
            con_cliente.resultset.last();
            mostrar_Dados();
        } catch(SQLException erro){
            JOptionPane.showMessageDialog(null,"Não foi possível posicionar no último registro: "+erro);
        }        // TODO add your handling code here:

    }//GEN-LAST:event_btnUtimoActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        codigoU.setText("");
        codigoL.setText("");
        dataE.setText("");
        telefonet.setText("");
        dataD.setText("");
        codigoU.setText("");
        codigoU.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed

        String nome = codigoL.getText();
        String data_nasc = dataE.getText();
        String telefone = telefonet.getText();
        String email = dataD.getText();

        try {
            String insert_sql = "INSERT INTO tbclientes (nome, telefone, email, dt_nasc) VALUES ('" + nome + "','" + telefone + "','" + email + "','" + data_nasc + "')"; con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso !", "Menssagem do programa",JOptionPane.INFORMATION_MESSAGE);
            con_cliente.executaSQL("select * from tbclientes order by cod");
            con_cliente.resultset.first();
            preencherTabela();
            mostrar_Dados();
        } catch(SQLException erroSQL) {
            JOptionPane.showMessageDialog(null, "\n erro na gravação :\n " + erroSQL, "mensagem do programa ", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_CadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        String nome = codigoL.getText();
        String data_nasc = dataE.getText();
        String telefone = telefonet.getText();
        String email = dataD.getText();
        String sql="";
        String msg="";

        try {
            if(codigoU.getText().equals("")){
                sql="insert into tbclientes (nome,telefone, email, dt_nasc) values ('" + nome + "','" + telefone + "','" + email + "','" + data_nasc + "')";
                msg="Gravação de um novo registro";
            }else{
                sql="update tbclientes set nome='" + nome + "',telefone='" + telefone + "', email='" + email + "', dt_nasc='" + data_nasc + "' where cod = " + codigoU.getText();
                msg="Alteração de registro";
            }

            con_cliente.statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,msg+" realizada com sucesso!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);

            con_cliente.executaSQL("select * from tbclientes order by cod");
            con_cliente.resultset.first();
            preencherTabela();
            mostrar_Dados();

        }catch(SQLException errosql){
            JOptionPane.showMessageDialog(null,"\n Erro na gravação :\n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        String nome = codigoL.getText();
        String data_nasc = dataE.getText();
        String telefone = telefonet.getText();
        String email = dataD.getText();

        String sql="";
        try {
            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ","Confirmar Exclusão", JOptionPane.YES_NO_OPTION,3);
            if (resposta==0){
                sql = "delete from tbclientes where cod = " + codigoU.getText();
                int excluir = con_cliente.statement.executeUpdate(sql);
                if (excluir==1){
                    JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
                    con_cliente.executaSQL("select * from tbclientes order by cod");
                    con_cliente.resultset.first();
                    preencherTabela();
                    posicionarRegistro();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Operação cancelada pelo usuário!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch (SQLException excecao){
            JOptionPane.showMessageDialog(null,"Erro na exclusão: "+excecao,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void JComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBox3ActionPerformed
  
 String opcaoSelecionada = (String) JComboBox3.getSelectedItem();
        
        switch (opcaoSelecionada) {
            case "Tela venda":
                new TelaVenda().setVisible(true);
                dispose();
                break;
            case "Tela emprestimo":
                new TelaEmprestimo().setVisible(true);
                dispose();
                break;
                case "Tela login":
                new TelaLogin().setVisible(true);
                dispose();
                break;
                 case "Cadastrar livro":
                new TelaCadastrarLivro().setVisible(true);
                dispose();
                break;
        } 
        
    }//GEN-LAST:event_JComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEmprestimo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JComboBox<String> JComboBox3;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnUtimo;
    private javax.swing.JLabel codigo;
    private javax.swing.JTextField codigoL;
    private javax.swing.JTextField codigoU;
    private javax.swing.JLabel data;
    private javax.swing.JTextField dataD;
    private javax.swing.JTextField dataE;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel telefone;
    private javax.swing.JTextField telefonet;
    // End of variables declaration//GEN-END:variables
}
